apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-ackee
  labels:
    app: mongo-ackee
    role: server
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-ackee
      role: server
      tier: backend
  template:
    metadata:
      labels:
        app: mongo-ackee
        role: server
        tier: backend
    spec:
      containers:
      - name: mongo-ackee
        image: ackee/docker-mongodb:3.2
        args:
          - --wiredTigerCacheSizeGB
          - '1'
          - --replSet
          - rs0
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 2Gi
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "b90-80FF435_0##2x2"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-ackee
  labels:
    app: mongo-ackee
    role: server
    tier: backend
spec:
  selector:
    app: mongo-ackee
    role: server
    tier: backend
  ports:
    - port: 27017
      targetPort: 27017
  type: NodePort
