#
# Mongo persistentni
#
# Je treba nastavit MONGO_INITDB_ROOT_USERNAME MONGO_INITDB_ROOT_PASSWORD
# Pote se pripojit rootem a uzivatele pro dane db (root pouze vytvari uzivatele)
# > use mojedb
# > db.createUser({user: "uzivatel",pwd: "heslo",roles: ["readWrite"]})
#
# Keep in sync with https://github.com/AckeeDevOps/docker-mongodb/blob/master/k8s/mongo-ackee.yaml !
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
    role: server
    tier: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongo
      role: server
      tier: backend
  template:
    metadata:
      labels:
        app: mongo
        role: server
        tier: backend
    spec:
      containers:
      - name: mongo
        image: ackee/docker-mongodb:3.2
        args:
          - --auth
          - --wiredTigerCacheSizeGB
          - '1'
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 2Gi
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "nicepassword"
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-production-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
    role: server
    tier: backend
spec:
  selector:
    app: mongo
    role: server
    tier: backend
  ports:
    - port: 27017
      targetPort: 27017
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-production-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
